spring.application.name=talentoemlinha

# Connection Settings
# Save data to a file in the user's home directory
spring.datasource.url=jdbc:h2:file:~/data/demo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# JPA/Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# debug=true

logging.level.root=ERROR
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG
